config/routes.rb
Gifmark::Application.routes.draw do
  get "/tag/:tag", to: 'gifs#index', as: :tag
  resources :gifs
  root :to => 'gifs#index'

end

app/models/gif.rb
require 'open-uri'
require 'digest/sha1'

class Gif < ActiveRecord::Base
  attr_accessible :title, :url, :response_code, :tag_list
  acts_as_taggable
  validates :title, presence: true
  validates :url  , presence: true, uniqueness: true,
                  format: { with: /^https*:\/\/[\w\S]+\/([\w\S]+\.gif)$/, message: "File url not valid" }
  validates :checksum, uniqueness: true, allow_blank: true

  before_save :verify_by_checksum, on: :create

  scope :ok, where(response_code: "200")

  def self.search query
    if query
  	  ok.basic_search(title: query)
    else
      ok.order('created_at DESC')
    end
  end

  def verify_by_checksum
  	self.checksum = Digest::SHA1.hexdigest( open(url) {|file| file.read } )
    self.response_code = "200" if self.checksum 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/gifs_controller.rb
class GifsController < ApplicationController
  respond_to :html, :json, :js
  before_filter :load, only: [ :show, :edit, :update, :destroy ]

  def index
    if params[:tag]
      @gifs = Gif.tagged_with(params[:tag])
    else
      @gifs = Gif.search(params[:q])
    end
    @gifs = @gifs.page(params[:page]).per(5)

    respond_with @gifs
  end

  def show
    respond_with @gif
  end

  def new
    @gif = Gif.new
  end

  def edit
  end

  def create
    @gif = Gif.create(params[:gif])
    if @gif.save
      redirect_to root_path, notice: 'Gif was successfully created.' 
    else
      render action: "new" 
    end
  end

  def update
    if @gif.update_attributes(params[:gif])
      redirect_to @gif, notice: 'Gif was successfully updated.' 
    else
      render action: "edit" 
    end
  end

  def destroy
    @gif.destroy
  end

  private

  def load
    @gif = Gif.find(params[:id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

  def home?
  	request.env['PATH_INFO'] == root_path
  end

  def fork_me url
  	link_to url do
  		image_tag "https://s3.amazonaws.com/github/ribbons/forkme_right_darkblue_121621.png", alt: "Fork me on GitHub", style: "position: absolute; top: 40px; right: 0; border: 0;"
  	end.html_safe
  end

  def tags_links tag_list
  	tag_list.map { |t| link_to t, tag_path(t) }.join(' ').html_safe
  end
end

app/helpers/gifs_helper.rb
module GifsHelper
end

app/views/gifs/_form.html.haml
.span8
  = form_for @gif do |f|
    - if @gif.errors.any?
      #error_explanation
        %h2= "#{pluralize(@gif.errors.count, "error")} prohibited this gif from being saved:"
        %ul
          - @gif.errors.full_messages.each do |msg|
            %li= msg
    %fieldset
      = f.text_field :title, placeholder: :title, class: "input-xlarge"
      %br/
      = f.text_field :url, placeholder: :url, class: "input-xxlarge"
      %br/
      = f.text_field :tag_list, placeholder: "tags (separated by commas)", class: "input-xlarge"
    %p.actions
      = f.submit "Save", class: 'btn btn-primary'

  %hr/
  .preview
    %h2 Preview
    - if @gif.persisted?
      %h3.title= @gif.title 
      %img{ src: "#{@gif.url}" }
    - else
      %h3.title
      %img

app/views/gifs/_gif.html.haml
.row.align-center
  %h2= gif.title
  = link_to image_tag( gif.url ), gif

app/views/gifs/_search.html.haml
.container
  .hero-unit
    %h1.logo= link_to "gifMark!", root_url
    %p Because the only thing that the humanity needs was... more gifs, and a place to find it.
    = form_tag root_path, method: :get, class: "pull-right" do
      .input-append
        = search_field_tag :q , nil, placeholder: "Search", class: 'span5'
        = submit_tag "NOW!", class: "btn btn-info"

app/views/gifs/edit.html.haml
%h1 Editing Gif

.row= render 'form'

app/views/gifs/index.html.haml
= render @gifs
.pull-right= paginate @gifs

app/views/gifs/new.html.haml
%h1 Add a new GIF

.row= render 'form'

app/views/gifs/show.html.haml
.align-center
  %h1= @gif.title
  %p= image_tag @gif.url, title: @gif.checksum
  %p
    %b Tags:
    = tags_links @gif.tag_list  

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title gifMark!
    = stylesheet_link_tag    :application, media: :all
    = javascript_include_tag :application 
    = csrf_meta_tags
  %body
    %header
      = render "shared/topnav"
      = render "gifs/search" if home?
    .container
      .main
        = yield
      .sidebar( data-spy="affix" data-offset-top="240" )
        #tag_cloud
          - tag_cloud Gif.tag_counts, %w[small medium large xlarge] do |tag, css_class| 
            = link_to tag.name, tag_path(tag.name), class: css_class
    %footer
      %p.align-center
        Copyright 
        = Time.now.year
        &copy; 3zcurdia

app/views/shared/_topnav.html.haml
.navbar.navbar-inverse.navbar-fixed-top
  .navbar-inner
    .container
      = link_to "gifMark!", root_url, class: 'brand'
      %ul.nav
        %li
          = link_to "Add New Gif", new_gif_path

      %ul.nav.pull-right
        %li
          = form_tag root_path, method: :get, class: "navbar-form" do
            = search_field_tag :q, nil, placeholder: "Search", class: "search-query"
        %li
          = link_to "Sing In", "/tag/404"

= fork_me "https://github.com/3zcurdia/gifmark"